"""Add salary_unit

Revision ID: 6117880e6a7f
Revises: ac08c8aaa9ad
Create Date: 2025-02-18 22:56:20.570944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6117880e6a7f'
down_revision: Union[str, None] = 'ac08c8aaa9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contracts', ['id'])
    op.add_column('jobs', sa.Column('salary_unit', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'positions', ['id'])
    op.create_unique_constraint(None, 'technologies', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'technologies', type_='unique')
    op.drop_constraint(None, 'positions', type_='unique')
    op.drop_column('jobs', 'salary_unit')
    op.drop_constraint(None, 'contracts', type_='unique')
    # ### end Alembic commands ###
