"""Add date_added column to jobs table

Revision ID: dd00c53051c7
Revises: 6117880e6a7f
Create Date: 2025-02-19 22:53:29.356736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd00c53051c7'
down_revision: Union[str, None] = '6117880e6a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('date_added', sa.DateTime(), nullable=True))

    # Update existing rows to set the current timestamp
    op.execute('UPDATE jobs SET date_added = NOW() WHERE date_added IS NULL')

    # Remove the server default
    op.alter_column('jobs', 'date_added', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'date_added')
    # ### end Alembic commands ###
